In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
# Preprocess the data
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
x = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and testing sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [14]:
## ANN Regression Problem statement

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [15]:
# Build the model
model = Sequential([Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
                   Dense(32, activation='relu'),
                   Dense(1)]) # Output layer for regression

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

/Users/akashsanjaypadwal/Desktop/AI/netural_networks/venv/lib/python3.14/site-packages/keras/src/layers/core/dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
# Set up the Tensorboard
log_dir = "regressionLogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [19]:
# setup Early Stopping
early_stopping_callback = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [20]:
# train the model
history = model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,
                    callbacks=[tensorflow_callback,early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 100384.6016 - mae: 100384.6016 - val_loss: 98544.4219 - val_mae: 98544.4219
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 99734.1172 - mae: 99734.1172 - val_loss: 97222.1016 - val_mae: 97222.1016
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 97431.5078 - mae: 97431.5078 - val_loss: 93824.6328 - val_mae: 93824.6328
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 92861.3047 - mae: 92861.3047 - val_loss: 88075.6172 - val_mae: 88075.6172
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 86088.1172 - mae: 86088.1172 - val_loss: 80443.2188 - val_mae: 80443.2188
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 77790.2969 - mae: 77790.2969 - val_loss: 72047.2734 - val_mae: 72047.2734
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 69185.5547 - mae: 69185.5547 - val_loss: 64258.7383 - val_mae: 64258.7383
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 61736.6133 - mae: 61736.6133 - val_loss: 58104.0938 - val_mae: 58104.0938
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 56404.5547 - mae: 56404.5547 - val_loss: 54141.8359 - val_mae: 54141.8359
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53216.0742 - mae: 53216.0742 - val_loss: 52079.4336 - val_mae: 52079.4336
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51545.3086 - mae: 51545.3086 - val_loss: 51184.3477 - val_mae: 51184.3477
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50786.0078 - mae: 50786.0078 - val_loss: 50853.0938 - val_mae: 50853.0938
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50467.9531 - mae: 50467.9531 - val_loss: 50702.7422 - val_mae: 50702.7422
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50323.4570 - mae: 50323.4570 - val_loss: 50621.0547 - val_mae: 50621.0547
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50239.9844 - mae: 50239.9844 - val_loss: 50567.2773 - val_mae: 50567.2773
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50177.3945 - mae: 50177.3945 - val_loss: 50523.1875 - val_mae: 50523.1875
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50125.3945 - mae: 50125.3945 - val_loss: 50485.2812 - val_mae: 50485.2812
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50080.8438 - mae: 50080.8438 - val_loss: 50454.4922 - val_mae: 50454.4922
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50042.9336 - mae: 50042.9336 - val_loss: 50429.4258 - val_mae: 50429.4258
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50009.1758 - mae: 50009.1758 - val_loss: 50409.2812 - val_mae: 50409.2812
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49978.2461 - mae: 49978.2461 - val_loss: 50391.5391 - val_mae: 50391.5391
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49949.6211 - mae: 49949.6211 - val_loss: 50373.5352 - val_mae: 50373.5352
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49923.0977 - mae: 49923.0977 - val_loss: 50357.5859 - val_mae: 50357.5859
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49897.8086 - mae: 49897.8086 - val_loss: 50344.6016 - val_mae: 50344.6016
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49874.1992 - mae: 49874.1992 - val_loss: 50330.7539 - val_mae: 50330.7539
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49852.3672 - mae: 49852.3672 - val_loss: 50317.4531 - val_mae: 50317.4531
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49831.6758 - mae: 49831.6758 - val_loss: 50307.1406 - val_mae: 50307.1406
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49811.7344 - mae: 49811.7344 - val_loss: 50296.5781 - val_mae: 50296.5781
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49792.4609 - mae: 49792.4609 - val_loss: 50288.8906 - val_mae: 50288.8906
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49774.5430 - mae: 49774.5430 - val_loss: 50282.3906 - val_mae: 50282.3906
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49757.0742 - mae: 49757.0742 - val_loss: 50277.3477 - val_mae: 50277.3477
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49740.9414 - mae: 49740.9414 - val_loss: 50273.0938 - val_mae: 50273.0938
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49725.6094 - mae: 49725.6094 - val_loss: 50266.1523 - val_mae: 50266.1523
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49711.1289 - mae: 49711.1289 - val_loss: 50259.8125 - val_mae: 50259.8125
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49696.9219 - mae: 49696.9219 - val_loss: 50252.4688 - val_mae: 50252.4688
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49683.4648 - mae: 49683.4648 - val_loss: 50248.0664 - val_mae: 50248.0664
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49670.8633 - mae: 49670.8633 - val_loss: 50241.1016 - val_mae: 50241.1016
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49658.9453 - mae: 49658.9453 - val_loss: 50235.8711 - val_mae: 50235.8711
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49647.4727 - mae: 49647.4727 - val_loss: 50231.6484 - val_mae: 50231.6484
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49636.7695 - mae: 49636.7695 - val_loss: 50226.4922 - val_mae: 50226.4922
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49626.6445 - mae: 49626.6445 - val_loss: 50224.6484 - val_mae: 50224.6484
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49616.6289 - mae: 49616.6289 - val_loss: 50221.6680 - val_mae: 50221.6680
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49606.8867 - mae: 49606.8867 - val_loss: 50218.6016 - val_mae: 50218.6016
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49598.0547 - mae: 49598.0547 - val_loss: 50216.4375 - val_mae: 50216.4375
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49589.3711 - mae: 49589.3711 - val_loss: 50216.5547 - val_mae: 50216.5547
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49580.8398 - mae: 49580.8398 - val_loss: 50216.5156 - val_mae: 50216.5156
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49572.7227 - mae: 49572.7227 - val_loss: 50216.9336 - val_mae: 50216.9336
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49564.9023 - mae: 49564.9023 - val_loss: 50217.2266 - val_mae: 50217.2266
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49557.2617 - mae: 49557.2617 - val_loss: 50216.6953 - val_mae: 50216.6953
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49550.0703 - mae: 49550.0703 - val_loss: 50217.1797 - val_mae: 50217.1797
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49542.7031 - mae: 49542.7031 - val_loss: 50216.1914 - val_mae: 50216.1914
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49535.7188 - mae: 49535.7188 - val_loss: 50215.9766 - val_mae: 50215.9766
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49529.0156 - mae: 49529.0156 - val_loss: 50217.1836 - val_mae: 50217.1836
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49522.0273 - mae: 49522.0273 - val_loss: 50218.8945 - val_mae: 50218.8945
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49515.2305 - mae: 49515.2305 - val_loss: 50220.5586 - val_mae: 50220.5586
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49509.5703 - mae: 49509.5703 - val_loss: 50220.7930 - val_mae: 50220.7930
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49503.2305 - mae: 49503.2305 - val_loss: 50221.9570 - val_mae: 50221.9570
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49497.1680 - mae: 49497.1680 - val_loss: 50224.1016 - val_mae: 50224.1016
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49491.0352 - mae: 49491.0352 - val_loss: 50225.4727 - val_mae: 50225.4727
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49485.3594 - mae: 49485.3594 - val_loss: 50228.1641 - val_mae: 50228.1641
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49479.6328 - mae: 49479.6328 - val_loss: 50230.8672 - val_mae: 50230.8672
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49474.0312 - mae: 49474.0312 - val_loss: 50233.7344 - val_mae: 50233.7344

In [21]:
## Evaluate the model
%load_ext tensorboard

In [25]:
%tensorboard  --logdir regressionLogs/fit/

Reusing TensorBoard on port 6008 (pid 78104), started 0:00:25 ago. (Use '!kill 78104' to kill it.)

In [26]:
# Evaluate model on the test data
test_loss,test_mae = model.evaluate(x_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - loss: 50215.9766 - mae: 50215.9766
Test MAE : 50215.9765625

In [27]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.